# Simple workflow for building Sphinx documentation and deploying to GitHub Pages
name: Build and Deploy Sphinx Docs

on:
  # Runs on pushes to the main branch
  push:
    branches:
      - "main"

  # Runs on pull requests
  pull_request:

  # Allows manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]

      - name: Build Sphinx documentation
        working-directory: docs
        run: |
          make html

      - name: Upload artifact for PR previews
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs
          path: docs/build/html

  deploy:
    if: github.ref_name == 'main' && github.event_name == 'push'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]

      - name: Build Sphinx documentation
        working-directory: docs
        run: |
          make html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
